Repository googleapis/nodejs-network-connectivity, pull requests merged in 2021-03, with the labels that each got.

#11 feat: Add state field in resources docs: Minor changes
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.md
  README.md
  linkinator.config.json
  protos/google/cloud/networkconnectivity/v1alpha1/hub.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1alpha1/gapic_metadata.json
  src/v1alpha1/hub_service_client.ts
  synth.metadata
Labels: api: networkconnectivity, cla: yes, context: partial

#14 fix: use repo metadata to populate nodejs CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: api: networkconnectivity, cla: yes, context: full

#15 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: networkconnectivity, automerge, cla: yes, context: full

#16 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: api: networkconnectivity, cla: yes
